// Silver Screen Sayings - iconic single-line movie quotes, each shown with its
// source (movie title and year). Only real, correctly-attributed lines are
// included - no invented dialogue.

(function () {
  var CLASSICS = [
    { quote: "Frankly, my dear, I don't give a damn.", source: "Gone with the Wind, 1939" },
    { quote: "After all, tomorrow is another day.", source: "Gone with the Wind, 1939" },
    { quote: "Here's looking at you, kid.", source: "Casablanca, 1942" },
    { quote: "We'll always have Paris.", source: "Casablanca, 1942" },
    { quote: "Louis, I think this is the beginning of a beautiful friendship.", source: "Casablanca, 1942" },
    { quote: "Of all the gin joints in all the towns in all the world, she walks into mine.", source: "Casablanca, 1942" },
    { quote: "Round up the usual suspects.", source: "Casablanca, 1942" },
    { quote: "Play it, Sam. Play 'As Time Goes By.'", source: "Casablanca, 1942" },
    { quote: "Toto, I've a feeling we're not in Kansas anymore.", source: "The Wizard of Oz, 1939" },
    { quote: "There's no place like home.", source: "The Wizard of Oz, 1939" },
    { quote: "I'll get you, my pretty, and your little dog too!", source: "The Wizard of Oz, 1939" },
    { quote: "Rosebud.", source: "Citizen Kane, 1941" },
    { quote: "I coulda been a contender.", source: "On the Waterfront, 1954" },
    { quote: "Fasten your seatbelts, it's going to be a bumpy night.", source: "All About Eve, 1950" },
    { quote: "Bond. James Bond.", source: "Dr. No, 1962" },
    { quote: "It was beauty killed the beast.", source: "King Kong, 1933" },
    { quote: "I'm gonna make him an offer he can't refuse.", source: "The Godfather, 1972" },
    { quote: "Keep your friends close, but your enemies closer.", source: "The Godfather Part II, 1974" },
    { quote: "Leave the gun. Take the cannoli.", source: "The Godfather, 1972" },
    { quote: "You talking to me?", source: "Taxi Driver, 1976" },
    { quote: "A census taker once tried to test me.", source: "The Silence of the Lambs, 1991" },
    { quote: "Houston, we have a problem.", source: "Apollo 13, 1995" },
    { quote: "Carpe diem. Seize the day.", source: "Dead Poets Society, 1989" },
    { quote: "O Captain! My Captain!", source: "Dead Poets Society, 1989" },
    { quote: "You can't handle the truth!", source: "A Few Good Men, 1992" },
    { quote: "I'm the king of the world!", source: "Titanic, 1997" },
    { quote: "You're gonna need a bigger boat.", source: "Jaws, 1975" },
    { quote: "Snap out of it!", source: "Moonstruck, 1987" },
    { quote: "Nobody puts Baby in a corner.", source: "Dirty Dancing, 1987" },
    { quote: "Roads? Where we're going, we don't need roads.", source: "Back to the Future, 1985" },
    { quote: "Great Scott!", source: "Back to the Future, 1985" },
    { quote: "Made it, Ma! Top of the world!", source: "White Heat, 1949" },
    { quote: "I want to be alone.", source: "Grand Hotel, 1932" },
    { quote: "I love the smell of napalm in the morning.", source: "Apocalypse Now, 1979" },
    { quote: "My precious.", source: "The Lord of the Rings: The Two Towers, 2002" },
    { quote: "With great power comes great responsibility.", source: "Spider-Man, 2002" },
    { quote: "Why so serious?", source: "The Dark Knight, 2008" },
    { quote: "E.T. phone home.", source: "E.T. the Extra-Terrestrial, 1982" },
    { quote: "I see dead people.", source: "The Sixth Sense, 1999" },
    { quote: "May the Force be with you.", source: "Star Wars, 1977" },
    { quote: "Is it safe?", source: "Marathon Man, 1976" },
    { quote: "Here's Johnny!", source: "The Shining, 1980" },
    { quote: "All work and no play makes Jack a dull boy.", source: "The Shining, 1980" },
    { quote: "Redrum.", source: "The Shining, 1980" },
    { quote: "I'm mad as hell, and I'm not going to take this anymore!", source: "Network, 1976" },
    { quote: "Greed, for lack of a better word, is good.", source: "Wall Street, 1987" },
    { quote: "There's no crying in baseball!", source: "A League of Their Own, 1992" },
    { quote: "It's alive! It's alive!", source: "Frankenstein, 1931" },
    { quote: "Elementary, my dear Watson.", source: "The Adventures of Sherlock Holmes, 1939" },
    { quote: "A boy's best friend is his mother.", source: "Psycho, 1960" },
    { quote: "We all go a little mad sometimes.", source: "Psycho, 1960" },
    { quote: "They call me Mister Tibbs!", source: "In the Heat of the Night, 1967" },
    { quote: "Plastics.", source: "The Graduate, 1967" },
    { quote: "Mrs. Robinson, you're trying to seduce me.", source: "The Graduate, 1967" },
    { quote: "What we've got here is failure to communicate.", source: "Cool Hand Luke, 1967" },
    { quote: "Attica! Attica!", source: "Dog Day Afternoon, 1975" },
    { quote: "Forget it, Jake. It's Chinatown.", source: "Chinatown, 1974" },
    { quote: "Badges? We don't need no stinking badges!", source: "The Treasure of the Sierra Madre, 1948" },
    { quote: "Klaatu barada nikto.", source: "The Day the Earth Stood Still, 1951" },
    { quote: "Gentlemen, you can't fight in here! This is the War Room!", source: "Dr. Strangelove, 1964" },
    { quote: "That'll be the day.", source: "The Searchers, 1956" },
    { quote: "Get your stinking paws off me, you damned dirty ape!", source: "Planet of the Apes, 1968" },
    { quote: "Soylent Green is people!", source: "Soylent Green, 1973" },
    { quote: "I'm walkin' here! I'm walkin' here!", source: "Midnight Cowboy, 1969" },
    { quote: "You know how to whistle, don't you? Just put your lips together and blow.", source: "To Have and Have Not, 1944" },
    { quote: "The stuff that dreams are made of.", source: "The Maltese Falcon, 1941" },
    { quote: "I drink your milkshake!", source: "There Will Be Blood, 2007" },
    { quote: "After all this time? Always.", source: "Harry Potter and the Deathly Hallows: Part 2, 2011" },
    { quote: "Why don't you come up sometime and see me?", source: "She Done Him Wrong, 1933" },
    { quote: "A martini. Shaken, not stirred.", source: "Goldfinger, 1964" },
    { quote: "Live and let die.", source: "Live and Let Die, 1974" },
    { quote: "Diamonds are forever.", source: "Diamonds Are Forever, 1971" }
  ];

  var ACTION = [
    { quote: "I'll be back.", source: "The Terminator, 1984" },
    { quote: "Hasta la vista, baby.", source: "Terminator 2: Judgment Day, 1991" },
    { quote: "Come with me if you want to live.", source: "Terminator 2: Judgment Day, 1991" },
    { quote: "I need your clothes, your boots, and your motorcycle.", source: "Terminator 2: Judgment Day, 1991" },
    { quote: "Get to the chopper!", source: "Predator, 1987" },
    { quote: "If it bleeds, we can kill it.", source: "Predator, 1987" },
    { quote: "Say hello to my little friend!", source: "Scarface, 1983" },
    { quote: "Do you feel lucky, punk?", source: "Dirty Harry, 1971" },
    { quote: "Go ahead, make my day.", source: "Sudden Impact, 1983" },
    { quote: "Welcome to the party, pal!", source: "Die Hard, 1988" },
    { quote: "Now I have a machine gun. Ho ho ho.", source: "Die Hard, 1988" },
    { quote: "Yippee-ki-yay!", source: "Die Hard, 1988" },
    { quote: "Live free or die hard.", source: "Live Free or Die Hard, 2007" },
    { quote: "Game over, man! Game over!", source: "Aliens, 1986" },
    { quote: "Get away from her, you bitch!", source: "Aliens, 1986" },
    { quote: "I feel the need — the need for speed.", source: "Top Gun, 1986" },
    { quote: "Talk to me, Goose.", source: "Top Gun, 1986" },
    { quote: "This is Sparta!", source: "300, 2006" },
    { quote: "Tonight, we dine in hell!", source: "300, 2006" },
    { quote: "Freedom!", source: "Braveheart, 1995" },
    { quote: "They may take our lives, but they'll never take our freedom!", source: "Braveheart, 1995" },
    { quote: "I am Iron Man.", source: "Iron Man, 2008" },
    { quote: "Avengers, assemble!", source: "Avengers: Endgame, 2019" },
    { quote: "Whatever it takes.", source: "Avengers: Endgame, 2019" },
    { quote: "I can do this all day.", source: "Captain America: Civil War, 2016" },
    { quote: "This is my BOOMSTICK!", source: "Army of Darkness, 1992" },
    { quote: "Groovy.", source: "Army of Darkness, 1992" },
    { quote: "Get off my plane!", source: "Air Force One, 1997" },
    { quote: "You shall not pass!", source: "The Lord of the Rings: The Fellowship of the Ring, 2001" },
    { quote: "One does not simply walk into Mordor.", source: "The Lord of the Rings: The Fellowship of the Ring, 2001" },
    { quote: "There can be only one.", source: "Highlander, 1986" },
    { quote: "I have a very particular set of skills.", source: "Taken, 2008" },
    { quote: "Release the Kraken!", source: "Clash of the Titans, 2010" },
    { quote: "It's a trap!", source: "Star Wars: Return of the Jedi, 1983" },
    { quote: "I find your lack of faith disturbing.", source: "Star Wars, 1977" },
    { quote: "The Force is strong with this one.", source: "Star Wars, 1977" },
    { quote: "Do or do not, there is no try.", source: "Star Wars: The Empire Strikes Back, 1980" },
    { quote: "Never tell me the odds!", source: "Star Wars: The Empire Strikes Back, 1980" },
    { quote: "I love it when a plan comes together.", source: "The A-Team, 2010" },
    { quote: "Adrian!", source: "Rocky, 1976" },
    { quote: "I have a bad feeling about this.", source: "Star Wars, 1977" },
    { quote: "Use the Force, Luke.", source: "Star Wars, 1977" },
    { quote: "Help me, Obi-Wan Kenobi. You're my only hope.", source: "Star Wars, 1977" },
    { quote: "No. I am your father.", source: "Star Wars: The Empire Strikes Back, 1980" },
    { quote: "That's no moon. It's a space station.", source: "Star Wars, 1977" },
    { quote: "Punch it, Chewie.", source: "Star Wars: The Force Awakens, 2015" },
    { quote: "Now this is podracing!", source: "Star Wars: The Phantom Menace, 1999" },
    { quote: "The Force will be with you. Always.", source: "Star Wars, 1977" },
    { quote: "It's over, Anakin. I have the high ground.", source: "Star Wars: Revenge of the Sith, 2005" },
    { quote: "This is where the fun begins.", source: "Star Wars: Revenge of the Sith, 2005" },
    { quote: "Execute Order 66.", source: "Star Wars: Revenge of the Sith, 2005" },
    { quote: "You either die a hero, or you live long enough to see yourself become the villain.", source: "The Dark Knight, 2008" },
    { quote: "I'm Batman.", source: "Batman Begins, 2005" },
    { quote: "I am Groot.", source: "Guardians of the Galaxy, 2014" },
    { quote: "Hulk smash!", source: "The Avengers, 2012" },
    { quote: "On your left.", source: "Captain America: The Winter Soldier, 2014" },
    { quote: "Wakanda forever!", source: "Black Panther, 2018" },
    { quote: "I am inevitable.", source: "Avengers: Infinity War, 2018" },
    { quote: "Perfectly balanced, as all things should be.", source: "Avengers: Infinity War, 2018" },
    { quote: "Dread it, run from it, destiny arrives all the same.", source: "Avengers: Infinity War, 2018" },
    { quote: "Live long and prosper.", source: "Star Trek II: The Wrath of Khan, 1982" },
    { quote: "KHAAAAN!", source: "Star Trek II: The Wrath of Khan, 1982" },
    { quote: "Resistance is futile.", source: "Star Trek: First Contact, 1996" },
    { quote: "Yo, Adrian!", source: "Rocky II, 1979" },
    { quote: "Flame on!", source: "Fantastic Four, 2005" },
    { quote: "It's clobberin' time!", source: "Fantastic Four, 2005" },
    { quote: "Fly, you fools!", source: "The Lord of the Rings: The Fellowship of the Ring, 2001" },
    { quote: "A wizard is never late, nor is he early. He arrives precisely when he means to.", source: "The Lord of the Rings: The Fellowship of the Ring, 2001" },
    { quote: "Even the smallest person can change the course of the future.", source: "The Lord of the Rings: The Fellowship of the Ring, 2001" },
    { quote: "One ring to rule them all.", source: "The Lord of the Rings: The Fellowship of the Ring, 2001" },
    { quote: "For Frodo.", source: "The Lord of the Rings: The Return of the King, 2003" },
    { quote: "You have my sword. And you have my bow. And my axe!", source: "The Lord of the Rings: The Fellowship of the Ring, 2001" }
  ];

  var COMEDY = [
    { quote: "I'll have what she's having.", source: "When Harry Met Sally, 1989" },
    { quote: "Well, nobody's perfect.", source: "Some Like It Hot, 1959" },
    { quote: "Bueller? Bueller?", source: "Ferris Bueller's Day Off, 1986" },
    { quote: "Life moves pretty fast. If you don't stop and look around once in a while, you could miss it.", source: "Ferris Bueller's Day Off, 1986" },
    { quote: "I am serious. And don't call me Shirley.", source: "Airplane!, 1980" },
    { quote: "Looks like I picked the wrong week to quit sniffing glue.", source: "Airplane!, 1980" },
    { quote: "Surely you can't be serious.", source: "Airplane!, 1980" },
    { quote: "It's just a flesh wound.", source: "Monty Python and the Holy Grail, 1975" },
    { quote: "Tis but a scratch.", source: "Monty Python and the Holy Grail, 1975" },
    { quote: "Ni!", source: "Monty Python and the Holy Grail, 1975" },
    { quote: "What is the air-speed velocity of an unladen swallow?", source: "Monty Python and the Holy Grail, 1975" },
    { quote: "Wax on, wax off.", source: "The Karate Kid, 1984" },
    { quote: "You're killing me, Smalls!", source: "The Sandlot, 1993" },
    { quote: "Life is like a box of chocolates, you never know what you're gonna get.", source: "Forrest Gump, 1994" },
    { quote: "Stupid is as stupid does.", source: "Forrest Gump, 1994" },
    { quote: "Run, Forrest, run!", source: "Forrest Gump, 1994" },
    { quote: "Show me the money!", source: "Jerry Maguire, 1996" },
    { quote: "You had me at hello.", source: "Jerry Maguire, 1996" },
    { quote: "Help me help you.", source: "Jerry Maguire, 1996" },
    { quote: "Great Odin's raven!", source: "Anchorman: The Legend of Ron Burgundy, 2004" },
    { quote: "I love lamp.", source: "Anchorman: The Legend of Ron Burgundy, 2004" },
    { quote: "Stay classy, San Diego.", source: "Anchorman: The Legend of Ron Burgundy, 2004" },
    { quote: "60% of the time, it works every time.", source: "Anchorman: The Legend of Ron Burgundy, 2004" },
    { quote: "I'm kind of a big deal.", source: "Anchorman: The Legend of Ron Burgundy, 2004" },
    { quote: "Just keep swimming.", source: "Finding Nemo, 2003" },
    { quote: "To infinity and beyond!", source: "Toy Story, 1995" },
    { quote: "There's a snake in my boot!", source: "Toy Story, 1995" },
    { quote: "Wilson!", source: "Cast Away, 2000" },
    { quote: "I solemnly swear that I am up to no good.", source: "Harry Potter and the Prisoner of Azkaban, 2004" },
    { quote: "You're a wizard, Harry.", source: "Harry Potter and the Sorcerer's Stone, 2001" },
    { quote: "That'll do, pig. That'll do.", source: "Babe, 1995" },
    { quote: "That's not a knife. This is a knife.", source: "Crocodile Dundee, 1986" },
    { quote: "You've got mail!", source: "You've Got Mail, 1998" },
    { quote: "As you wish.", source: "The Princess Bride, 1987" },
    { quote: "My name is Inigo Montoya. You killed my father. Prepare to die.", source: "The Princess Bride, 1987" },
    { quote: "Inconceivable!", source: "The Princess Bride, 1987" },
    { quote: "Have fun storming the castle!", source: "The Princess Bride, 1987" },
    { quote: "You can't sit with us.", source: "Mean Girls, 2004" },
    { quote: "That's so fetch.", source: "Mean Girls, 2004" },
    { quote: "On Wednesdays we wear pink.", source: "Mean Girls, 2004" },
    { quote: "Toga! Toga!", source: "Animal House, 1978" },
    { quote: "Fat, drunk, and stupid is no way to go through life, son.", source: "Animal House, 1978" },
    { quote: "Wingardium Leviosa.", source: "Harry Potter and the Sorcerer's Stone, 2001" },
    { quote: "Alohomora.", source: "Harry Potter and the Sorcerer's Stone, 2001" },
    { quote: "Expecto Patronum.", source: "Harry Potter and the Prisoner of Azkaban, 2004" },
    { quote: "Hakuna Matata.", source: "The Lion King, 1994" },
    { quote: "Life is a banquet, and most poor suckers are starving to death!", source: "Auntie Mame, 1958" },
    { quote: "Shake and bake!", source: "Talladega Nights: The Ballad of Ricky Bobby, 2006" },
    { quote: "I wanna go fast!", source: "Talladega Nights: The Ballad of Ricky Bobby, 2006" },
    { quote: "I'm a golden god!", source: "Almost Famous, 2000" },
    { quote: "You complete me.", source: "Jerry Maguire, 1996" },
    { quote: "Heroes get remembered, but legends never die.", source: "The Sandlot, 1993" },
    { quote: "For-ev-er.", source: "The Sandlot, 1993" },
    { quote: "Chicks dig the long ball.", source: "The Sandlot, 1993" },
    { quote: "You play ball like a girl!", source: "The Sandlot, 1993" },
    { quote: "The question isn't 'what are we going to do,' the question is 'what aren't we going to do?'", source: "Ferris Bueller's Day Off, 1986" },
    { quote: "Save Ferris.", source: "Ferris Bueller's Day Off, 1986" },
    { quote: "You know what they call a Quarter Pounder with Cheese in France?", source: "Pulp Fiction, 1994" },
    { quote: "Royale with cheese.", source: "Pulp Fiction, 1994" },
    { quote: "I feel like I'm taking crazy pills!", source: "Zoolander, 2001" },
    { quote: "Derelicte.", source: "Zoolander, 2001" },
    { quote: "Blue Steel.", source: "Zoolander, 2001" },
    { quote: "We're not worthy! We're not worthy!", source: "Wayne's World, 1992" },
    { quote: "Party on, Wayne. Party on, Garth.", source: "Wayne's World, 1992" },
    { quote: "Vote for Pedro.", source: "Napoleon Dynamite, 2004" },
    { quote: "I caught you a delicious bass.", source: "Napoleon Dynamite, 2004" },
    { quote: "Buddy the Elf, what's your favorite color?", source: "Elf, 2003" },
    { quote: "Son of a nutcracker!", source: "Elf, 2003" },
    { quote: "The best way to spread Christmas cheer is singing loud for all to hear.", source: "Elf, 2003" },
    { quote: "I'm a cotton-headed ninny-muggins.", source: "Elf, 2003" },
    { quote: "Did we just become best friends?", source: "Step Brothers, 2008" },
    { quote: "Boats and hoes.", source: "Step Brothers, 2008" },
    { quote: "The Dude abides.", source: "The Big Lebowski, 1998" },
    { quote: "That rug really tied the room together.", source: "The Big Lebowski, 1998" },
    { quote: "Yeah, well, you know, that's just, like, your opinion, man.", source: "The Big Lebowski, 1998" }
  ];

  var SCIFI = [
    { quote: "All those moments will be lost in time, like tears in rain.", source: "Blade Runner, 1982" },
    { quote: "I've seen things you people wouldn't believe.", source: "Blade Runner, 1982" },
    { quote: "Wake up, Neo.", source: "The Matrix, 1999" },
    { quote: "There is no spoon.", source: "The Matrix, 1999" },
    { quote: "I know kung fu.", source: "The Matrix, 1999" },
    { quote: "Welcome to the real world.", source: "The Matrix, 1999" },
    { quote: "Follow the white rabbit.", source: "The Matrix, 1999" },
    { quote: "Life, uh, finds a way.", source: "Jurassic Park, 1993" },
    { quote: "Welcome... to Jurassic Park.", source: "Jurassic Park, 1993" },
    { quote: "Hold on to your butts.", source: "Jurassic Park, 1993" },
    { quote: "Must go faster.", source: "Jurassic Park, 1993" },
    { quote: "Clever girl.", source: "Jurassic Park, 1993" },
    { quote: "We spared no expense.", source: "Jurassic Park, 1993" },
    { quote: "It's a Unix system! I know this!", source: "Jurassic Park, 1993" },
    { quote: "Dinosaurs eat man. Woman inherits the Earth.", source: "The Lost World: Jurassic Park, 1997" },
    { quote: "My God, it's full of stars.", source: "2010: The Year We Make Contact, 1984" },
    { quote: "Open the pod bay doors, HAL.", source: "2001: A Space Odyssey, 1968" },
    { quote: "I'm sorry, Dave, I'm afraid I can't do that.", source: "2001: A Space Odyssey, 1968" },
    { quote: "Daisy, Daisy, give me your answer do.", source: "2001: A Space Odyssey, 1968" },
    { quote: "This is heavy.", source: "Back to the Future, 1985" },
    { quote: "1.21 gigawatts!", source: "Back to the Future, 1985" },
    { quote: "Nobody calls me chicken.", source: "Back to the Future, 1985" },
    { quote: "Love is the one thing that transcends time and space.", source: "Interstellar, 2014" },
    { quote: "We used to look up at the sky and wonder at our place in the stars.", source: "Interstellar, 2014" },
    { quote: "Do not go gentle into that good night.", source: "Interstellar, 2014" },
    { quote: "Judgment day is inevitable.", source: "Terminator 2: Judgment Day, 1991" },
    { quote: "The future is not set. There is no fate but what we make for ourselves.", source: "Terminator 2: Judgment Day, 1991" },
    { quote: "This means something. This is important.", source: "Close Encounters of the Third Kind, 1977" },
    { quote: "Welcome to Earth.", source: "Independence Day, 1996" },
    { quote: "Today we celebrate our Independence Day!", source: "Independence Day, 1996" },
    { quote: "Multipass.", source: "The Fifth Element, 1997" },
    { quote: "Big bada boom.", source: "The Fifth Element, 1997" },
    { quote: "Dead or alive, you're coming with me.", source: "RoboCop, 1987" },
    { quote: "I'd buy that for a dollar!", source: "RoboCop, 1987" },
    { quote: "Get your ass to Mars.", source: "Total Recall, 1990" },
    { quote: "See you at the party, Richter!", source: "Total Recall, 1990" },
    { quote: "Consider that a divorce.", source: "Total Recall, 1990" },
    { quote: "Everybody runs.", source: "Minority Report, 2002" },
    { quote: "Fear is the mind-killer.", source: "Dune, 2021" },
    { quote: "The spice must flow.", source: "Dune, 1984" },
    { quote: "If it's just us, it seems like an awful waste of space.", source: "Contact, 1997" }
  ];

  var CATEGORIES = [
    { id: "classics", label: "Classics", icon: "🎩" },
    { id: "action", label: "Action", icon: "💥" },
    { id: "comedy", label: "Comedy", icon: "😂" },
    { id: "scifi", label: "Sci-Fi", icon: "🛸" },
    { id: "random", label: "Random", icon: "🎲" },
    { id: "favorites", label: "Favorites", icon: "❤️" }
  ];

  window.SCREEN_DATA = { classics: CLASSICS, action: ACTION, comedy: COMEDY, scifi: SCIFI };
  window.SCREEN_CATEGORIES = CATEGORIES;
})();
