// Silver Screen Sayings - iconic single-line movie quotes, each shown with its
// source (movie title and year). Only real, correctly-attributed lines are
// included - no invented dialogue.

(function () {
  var CLASSICS = [
    { quote: "Frankly, my dear, I don't give a damn.", source: "Gone with the Wind, 1939" },
    { quote: "After all, tomorrow is another day.", source: "Gone with the Wind, 1939" },
    { quote: "Here's looking at you, kid.", source: "Casablanca, 1942" },
    { quote: "We'll always have Paris.", source: "Casablanca, 1942" },
    { quote: "Louis, I think this is the beginning of a beautiful friendship.", source: "Casablanca, 1942" },
    { quote: "Of all the gin joints in all the towns in all the world, she walks into mine.", source: "Casablanca, 1942" },
    { quote: "Round up the usual suspects.", source: "Casablanca, 1942" },
    { quote: "Play it, Sam. Play 'As Time Goes By.'", source: "Casablanca, 1942" },
    { quote: "Toto, I've a feeling we're not in Kansas anymore.", source: "The Wizard of Oz, 1939" },
    { quote: "There's no place like home.", source: "The Wizard of Oz, 1939" },
    { quote: "I'll get you, my pretty, and your little dog too!", source: "The Wizard of Oz, 1939" },
    { quote: "Rosebud.", source: "Citizen Kane, 1941" },
    { quote: "I coulda been a contender.", source: "On the Waterfront, 1954" },
    { quote: "Fasten your seatbelts, it's going to be a bumpy night.", source: "All About Eve, 1950" },
    { quote: "Bond. James Bond.", source: "Dr. No, 1962" },
    { quote: "It was beauty killed the beast.", source: "King Kong, 1933" },
    { quote: "I'm gonna make him an offer he can't refuse.", source: "The Godfather, 1972" },
    { quote: "Keep your friends close, but your enemies closer.", source: "The Godfather Part II, 1974" },
    { quote: "Leave the gun. Take the cannoli.", source: "The Godfather, 1972" },
    { quote: "You talking to me?", source: "Taxi Driver, 1976" },
    { quote: "A census taker once tried to test me.", source: "The Silence of the Lambs, 1991" },
    { quote: "Houston, we have a problem.", source: "Apollo 13, 1995" },
    { quote: "Carpe diem. Seize the day.", source: "Dead Poets Society, 1989" },
    { quote: "O Captain! My Captain!", source: "Dead Poets Society, 1989" },
    { quote: "You can't handle the truth!", source: "A Few Good Men, 1992" },
    { quote: "I'm the king of the world!", source: "Titanic, 1997" },
    { quote: "You're gonna need a bigger boat.", source: "Jaws, 1975" },
    { quote: "Snap out of it!", source: "Moonstruck, 1987" },
    { quote: "Nobody puts Baby in a corner.", source: "Dirty Dancing, 1987" },
    { quote: "Roads? Where we're going, we don't need roads.", source: "Back to the Future, 1985" },
    { quote: "Great Scott!", source: "Back to the Future, 1985" },
    { quote: "Made it, Ma! Top of the world!", source: "White Heat, 1949" },
    { quote: "I want to be alone.", source: "Grand Hotel, 1932" },
    { quote: "I love the smell of napalm in the morning.", source: "Apocalypse Now, 1979" },
    { quote: "My precious.", source: "The Lord of the Rings: The Two Towers, 2002" },
    { quote: "With great power comes great responsibility.", source: "Spider-Man, 2002" },
    { quote: "Why so serious?", source: "The Dark Knight, 2008" },
    { quote: "E.T. phone home.", source: "E.T. the Extra-Terrestrial, 1982" },
    { quote: "I see dead people.", source: "The Sixth Sense, 1999" },
    { quote: "May the Force be with you.", source: "Star Wars, 1977" }
  ];

  var ACTION = [
    { quote: "I'll be back.", source: "The Terminator, 1984" },
    { quote: "Hasta la vista, baby.", source: "Terminator 2: Judgment Day, 1991" },
    { quote: "Come with me if you want to live.", source: "Terminator 2: Judgment Day, 1991" },
    { quote: "I need your clothes, your boots, and your motorcycle.", source: "Terminator 2: Judgment Day, 1991" },
    { quote: "Get to the chopper!", source: "Predator, 1987" },
    { quote: "If it bleeds, we can kill it.", source: "Predator, 1987" },
    { quote: "Say hello to my little friend!", source: "Scarface, 1983" },
    { quote: "Do you feel lucky, punk?", source: "Dirty Harry, 1971" },
    { quote: "Go ahead, make my day.", source: "Sudden Impact, 1983" },
    { quote: "Welcome to the party, pal!", source: "Die Hard, 1988" },
    { quote: "Now I have a machine gun. Ho ho ho.", source: "Die Hard, 1988" },
    { quote: "Yippee-ki-yay!", source: "Die Hard, 1988" },
    { quote: "Live free or die hard.", source: "Live Free or Die Hard, 2007" },
    { quote: "Game over, man! Game over!", source: "Aliens, 1986" },
    { quote: "Get away from her, you bitch!", source: "Aliens, 1986" },
    { quote: "I feel the need — the need for speed.", source: "Top Gun, 1986" },
    { quote: "Talk to me, Goose.", source: "Top Gun, 1986" },
    { quote: "This is Sparta!", source: "300, 2006" },
    { quote: "Tonight, we dine in hell!", source: "300, 2006" },
    { quote: "Freedom!", source: "Braveheart, 1995" },
    { quote: "They may take our lives, but they'll never take our freedom!", source: "Braveheart, 1995" },
    { quote: "I am Iron Man.", source: "Iron Man, 2008" },
    { quote: "Avengers, assemble!", source: "Avengers: Endgame, 2019" },
    { quote: "Whatever it takes.", source: "Avengers: Endgame, 2019" },
    { quote: "I can do this all day.", source: "Captain America: Civil War, 2016" },
    { quote: "This is my BOOMSTICK!", source: "Army of Darkness, 1992" },
    { quote: "Groovy.", source: "Army of Darkness, 1992" },
    { quote: "Get off my plane!", source: "Air Force One, 1997" },
    { quote: "You shall not pass!", source: "The Lord of the Rings: The Fellowship of the Ring, 2001" },
    { quote: "One does not simply walk into Mordor.", source: "The Lord of the Rings: The Fellowship of the Ring, 2001" },
    { quote: "There can be only one.", source: "Highlander, 1986" },
    { quote: "I have a very particular set of skills.", source: "Taken, 2008" },
    { quote: "Release the Kraken!", source: "Clash of the Titans, 2010" },
    { quote: "It's a trap!", source: "Star Wars: Return of the Jedi, 1983" },
    { quote: "I find your lack of faith disturbing.", source: "Star Wars, 1977" },
    { quote: "The Force is strong with this one.", source: "Star Wars, 1977" },
    { quote: "Do or do not, there is no try.", source: "Star Wars: The Empire Strikes Back, 1980" },
    { quote: "Never tell me the odds!", source: "Star Wars: The Empire Strikes Back, 1980" },
    { quote: "I love it when a plan comes together.", source: "The A-Team, 2010" },
    { quote: "Adrian!", source: "Rocky, 1976" }
  ];

  var COMEDY = [
    { quote: "I'll have what she's having.", source: "When Harry Met Sally, 1989" },
    { quote: "Well, nobody's perfect.", source: "Some Like It Hot, 1959" },
    { quote: "Bueller? Bueller?", source: "Ferris Bueller's Day Off, 1986" },
    { quote: "Life moves pretty fast. If you don't stop and look around once in a while, you could miss it.", source: "Ferris Bueller's Day Off, 1986" },
    { quote: "I am serious. And don't call me Shirley.", source: "Airplane!, 1980" },
    { quote: "Looks like I picked the wrong week to quit sniffing glue.", source: "Airplane!, 1980" },
    { quote: "Surely you can't be serious.", source: "Airplane!, 1980" },
    { quote: "It's just a flesh wound.", source: "Monty Python and the Holy Grail, 1975" },
    { quote: "Tis but a scratch.", source: "Monty Python and the Holy Grail, 1975" },
    { quote: "Ni!", source: "Monty Python and the Holy Grail, 1975" },
    { quote: "What is the air-speed velocity of an unladen swallow?", source: "Monty Python and the Holy Grail, 1975" },
    { quote: "Wax on, wax off.", source: "The Karate Kid, 1984" },
    { quote: "You're killing me, Smalls!", source: "The Sandlot, 1993" },
    { quote: "Life is like a box of chocolates, you never know what you're gonna get.", source: "Forrest Gump, 1994" },
    { quote: "Stupid is as stupid does.", source: "Forrest Gump, 1994" },
    { quote: "Run, Forrest, run!", source: "Forrest Gump, 1994" },
    { quote: "Show me the money!", source: "Jerry Maguire, 1996" },
    { quote: "You had me at hello.", source: "Jerry Maguire, 1996" },
    { quote: "Help me help you.", source: "Jerry Maguire, 1996" },
    { quote: "Great Odin's raven!", source: "Anchorman: The Legend of Ron Burgundy, 2004" },
    { quote: "I love lamp.", source: "Anchorman: The Legend of Ron Burgundy, 2004" },
    { quote: "Stay classy, San Diego.", source: "Anchorman: The Legend of Ron Burgundy, 2004" },
    { quote: "60% of the time, it works every time.", source: "Anchorman: The Legend of Ron Burgundy, 2004" },
    { quote: "I'm kind of a big deal.", source: "Anchorman: The Legend of Ron Burgundy, 2004" },
    { quote: "Just keep swimming.", source: "Finding Nemo, 2003" },
    { quote: "To infinity and beyond!", source: "Toy Story, 1995" },
    { quote: "There's a snake in my boot!", source: "Toy Story, 1995" },
    { quote: "Wilson!", source: "Cast Away, 2000" },
    { quote: "I solemnly swear that I am up to no good.", source: "Harry Potter and the Prisoner of Azkaban, 2004" },
    { quote: "You're a wizard, Harry.", source: "Harry Potter and the Sorcerer's Stone, 2001" },
    { quote: "That'll do, pig. That'll do.", source: "Babe, 1995" },
    { quote: "That's not a knife. This is a knife.", source: "Crocodile Dundee, 1986" },
    { quote: "You've got mail!", source: "You've Got Mail, 1998" },
    { quote: "As you wish.", source: "The Princess Bride, 1987" },
    { quote: "My name is Inigo Montoya. You killed my father. Prepare to die.", source: "The Princess Bride, 1987" },
    { quote: "Inconceivable!", source: "The Princess Bride, 1987" },
    { quote: "Have fun storming the castle!", source: "The Princess Bride, 1987" },
    { quote: "You can't sit with us.", source: "Mean Girls, 2004" },
    { quote: "That's so fetch.", source: "Mean Girls, 2004" },
    { quote: "On Wednesdays we wear pink.", source: "Mean Girls, 2004" }
  ];

  var CATEGORIES = [
    { id: "classics", label: "Classics", icon: "🎩" },
    { id: "action", label: "Action", icon: "💥" },
    { id: "comedy", label: "Comedy", icon: "😂" },
    { id: "random", label: "Random", icon: "🎲" },
    { id: "favorites", label: "Favorites", icon: "❤️" }
  ];

  window.SCREEN_DATA = { classics: CLASSICS, action: ACTION, comedy: COMEDY };
  window.SCREEN_CATEGORIES = CATEGORIES;
})();
